[0m[[0minfo[0m] [0mRunning RemoteBossApp [0m
[0m[[0mdebug[0m] [0mStarting sandboxed run...[0m
[0m[[0mdebug[0m] [0mWaiting for threads to exit or System.exit to be called.[0m
[0m[[0mdebug[0m] [0m  Classpath:[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/ScalaWork/Project1BonusClient08/project1-remote/target/scala-2.10/classes[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.sbt/boot/scala-2.10.2/lib/scala-library.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.2.1.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/com.typesafe/config/bundles/config-1.0.2.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/com.typesafe.akka/akka-remote_2.10/bundles/akka-remote_2.10-2.2.1.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/io.netty/netty/bundles/netty-3.6.6.Final.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/com.google.protobuf/protobuf-java/jars/protobuf-java-2.4.1.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar[0m
[0m[[0mdebug[0m] [0m	/cise/homes/xuxu/.ivy2/cache/com.typesafe.akka/akka-kernel_2.10/jars/akka-kernel_2.10-2.2.1.jar[0m
[0m[[0mdebug[0m] [0mWaiting for thread run-main to exit[0m
[0m[[31merror[0m] [0m(run-main) org.jboss.netty.channel.ChannelException: Failed to bind to: lin114-08.cise.ufl.edu/128.227.248.174:2552[0m
org.jboss.netty.channel.ChannelException: Failed to bind to: lin114-08.cise.ufl.edu/128.227.248.174:2552
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:382)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:379)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:366)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:290)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
[0m[[0mdebug[0m] [0m	Thread run-main exited.[0m
[0m[[0mdebug[0m] [0mWaiting for thread New I/O worker #2 to exit[0m
